# Lab 2.1 Numpy

Name: Anas Kabir

Course: Machine Learning

Performed in: Jupyter Notebook (Anaconda)

Objective:
To learn basic Numpy operations including arrays, indexing, shape, dimensions, and mathematical operations.

In [1]:
import numpy as np

print("Numpy imported successfully")

Numpy imported successfully


In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [5]:
print("Dimension of Array:")

print(arr2.ndim)


print("Shape of Array:")

print(arr2.shape)


print("Size of Array:")

print(arr2.size)

Dimension of Array:
2
Shape of Array:
(2, 3)
Size of Array:
6


In [6]:
numbers = np.arange(1, 11)


print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
zeros_array = np.zeros((3,3))

ones_array = np.ones((3,3))


print("Zeros Array:")

print(zeros_array)


print("Ones Array:")

print(ones_array)

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
random_array = np.random.rand(3,3)


print("Random Array:")

print(random_array)

Random Array:
[[0.46499489 0.24544873 0.08064051]
 [0.74031388 0.76215258 0.38198094]
 [0.28970685 0.27234277 0.75149875]]


In [9]:
array = np.arange(1,13)


reshape_array = array.reshape(3,4)


print("Original Array:")

print(array)


print("Reshaped Array:")

print(reshape_array)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print("First Element:")

print(arr[0])


print("Last Element:")

print(arr[-1])


print("2D Array Element:")

print(arr2[1,2])

First Element:
1
Last Element:
5
2D Array Element:
6


In [11]:
array1 = np.array([10,20,30,40])

array2 = np.array([1,2,3,4])


print("Addition:")

print(array1 + array2)


print("Subtraction:")

print(array1 - array2)


print("Multiplication:")

print(array1 * array2)


print("Division:")

print(array1 / array2)

Addition:
[11 22 33 44]
Subtraction:
[ 9 18 27 36]
Multiplication:
[ 10  40  90 160]
Division:
[10. 10. 10. 10.]


In [12]:
data = np.array([5,10,15,20,25])


print("Mean:")

print(np.mean(data))


print("Maximum Value:")

print(np.max(data))


print("Minimum Value:")

print(np.min(data))


print("Standard Deviation:")

print(np.std(data))

Mean:
15.0
Maximum Value:
25
Minimum Value:
5
Standard Deviation:
7.0710678118654755


In [13]:
np.save(
    "numpy_array.npy",
    data
)


print("Numpy array saved successfully")

Numpy array saved successfully


## Conclusion

In this lab, NumPy library was used for numerical computing.

Different operations including array creation, dimensions, reshaping, indexing, and mathematical calculations were performed.

Statistical operations such as mean, maximum, minimum, and standard deviation were also implemented.

NumPy provides fast and efficient handling of numerical data for machine learning applications.